language: perl
perl:
- "5.14"
before_install:
- git clone git://github.com/haarg/perl-travis-helper
- source perl-travis-helper/init
- build-perl
- perl -V
install:
- export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
- cpanm --quiet --notest Devel::Cover::Report::Coveralls
- cpanm --quiet --notest --skip-satisfied --installdeps .
script: 
- PERL5OPT='-MDevel::Cover=+ignore,/usr,\.t$,/prove$,TestHarness\.pm$,-coverage,statement,branch,condition,path,subroutine' prove -lrvm t
after_success:
- cover -report coveralls
